language: python
python:
    - "3.6"
install:
    - pip install click numpy pysam flake8
script:
    - python3 -m doctest ampliviz.py
    # TODO compare actual dot output graph files using sample ampliconarchitect
    # graph (figure out which graphs I'm clear to use)
    - flake8 ampliviz.py
